# Generated by Django 5.0.7 on 2024-07-13 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carausel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='img/slider')),
                ('titulo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='descricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='img/home/logo-Text.svg', verbose_name='Imagem de Exibição')),
                ('narrativa', models.TextField(verbose_name='Narrativa')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='img/geral/logo.svg', verbose_name='Logo')),
                ('imagem2', models.ImageField(blank=True, null=True, upload_to='img/geral/deco-verdeClaro.svg', verbose_name='Imagem de Exibição')),
            ],
        ),
        migrations.CreateModel(
            name='nossos_servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulação')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='img/servicos', verbose_name='Imagem de Exibição')),
                ('titulo2', models.CharField(max_length=100, verbose_name='Titulo')),
            ],
        ),
    ]
