# Generated by Django 5.0.7 on 2024-07-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_remove_carausel_titulo_alter_carausel_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carausel',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='core/static/img/slider', verbose_name='Foto de Exibição'),
        ),
    ]
