# Generated by Django 5.0.7 on 2024-07-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_alter_carausel_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='carausel',
            name='imagem2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto de Exibição'),
        ),
    ]
