# Generated by Django 5.0.7 on 2024-07-13 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0004_carausel_imagem2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carausel',
            name='imagem2',
        ),
    ]
