# Generated by Django 5.0.7 on 2024-07-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0005_remove_carausel_imagem2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='descricao',
            options={'verbose_name': 'descrição', 'verbose_name_plural': 'descrições'},
        ),
        migrations.AlterField(
            model_name='descricao',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='core/static/img/home/logo-Text.svg', verbose_name='Imagem de Exibição'),
        ),
        migrations.AlterModelTable(
            name='descricao',
            table='descricao',
        ),
    ]
