# Generated by Django 5.0.7 on 2024-07-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0006_alter_descricao_options_alter_descricao_imagem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descricao',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='descricao',
            name='imagem2',
        ),
        migrations.AddField(
            model_name='descricao',
            name='logo2',
            field=models.ImageField(blank=True, null=True, upload_to='core/static/img/geral/logo.svg', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='descricao',
            name='logo3',
            field=models.ImageField(blank=True, null=True, upload_to='core/static/img/geral/deco-verdeClaro.svg', verbose_name='Imagem de Exibição'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='core/static/img/home/logo-Text.svg', verbose_name='Imagem de Exibição'),
        ),
    ]
